var CHAR_TO_KEYCODE = {
    ' ': { keyCode: 32 },
    '0': { keyCode: 48 },
    '1': { keyCode: 49 },
    '2': { keyCode: 50 },
    '3': { keyCode: 51 },
    '4': { keyCode: 52 },
    '5': { keyCode: 53 },
    '6': { keyCode: 54 },
    '7': { keyCode: 55 },
    '8': { keyCode: 56 },
    '9': { keyCode: 57 },
    ')': { keyCode: 48, shiftKey: true },
    '!': { keyCode: 49, shiftKey: true },
    '@': { keyCode: 50, shiftKey: true },
    '#': { keyCode: 51, shiftKey: true },
    '$': { keyCode: 52, shiftKey: true },
    '%': { keyCode: 53, shiftKey: true },
    '^': { keyCode: 54, shiftKey: true },
    '&': { keyCode: 55, shiftKey: true },
    '*': { keyCode: 56, shiftKey: true },
    '(': { keyCode: 57, shiftKey: true },
    'a': { keyCode: 65 },
    'b': { keyCode: 66 },
    'c': { keyCode: 67 },
    'd': { keyCode: 68 },
    'e': { keyCode: 69 },
    'f': { keyCode: 70 },
    'g': { keyCode: 71 },
    'h': { keyCode: 72 },
    'i': { keyCode: 73 },
    'j': { keyCode: 74 },
    'k': { keyCode: 75 },
    'l': { keyCode: 76 },
    'm': { keyCode: 77 },
    'n': { keyCode: 78 },
    'o': { keyCode: 79 },
    'p': { keyCode: 80 },
    'q': { keyCode: 81 },
    'r': { keyCode: 82 },
    's': { keyCode: 83 },
    't': { keyCode: 84 },
    'u': { keyCode: 85 },
    'v': { keyCode: 86 },
    'w': { keyCode: 87 },
    'x': { keyCode: 88 },
    'y': { keyCode: 89 },
    'z': { keyCode: 90 },
    'A': { keyCode: 65, shiftKey: true },
    'B': { keyCode: 66, shiftKey: true },
    'C': { keyCode: 67, shiftKey: true },
    'D': { keyCode: 68, shiftKey: true },
    'E': { keyCode: 69, shiftKey: true },
    'F': { keyCode: 70, shiftKey: true },
    'G': { keyCode: 71, shiftKey: true },
    'H': { keyCode: 72, shiftKey: true },
    'I': { keyCode: 73, shiftKey: true },
    'J': { keyCode: 74, shiftKey: true },
    'K': { keyCode: 75, shiftKey: true },
    'L': { keyCode: 76, shiftKey: true },
    'M': { keyCode: 77, shiftKey: true },
    'N': { keyCode: 78, shiftKey: true },
    'O': { keyCode: 79, shiftKey: true },
    'P': { keyCode: 80, shiftKey: true },
    'Q': { keyCode: 81, shiftKey: true },
    'R': { keyCode: 82, shiftKey: true },
    'S': { keyCode: 83, shiftKey: true },
    'T': { keyCode: 84, shiftKey: true },
    'U': { keyCode: 85, shiftKey: true },
    'V': { keyCode: 86, shiftKey: true },
    'W': { keyCode: 87, shiftKey: true },
    'X': { keyCode: 88, shiftKey: true },
    'Y': { keyCode: 89, shiftKey: true },
    'Z': { keyCode: 90, shiftKey: true },
    ';': { keyCode: 186 },
    '=': { keyCode: 187 },
    ',': { keyCode: 188 },
    '-': { keyCode: 189 },
    '.': { keyCode: 190 },
    '/': { keyCode: 191 },
    '`': { keyCode: 192 },
    '[': { keyCode: 219 },
    '\\': { keyCode: 220 },
    ']': { keyCode: 221 },
    '\'': { keyCode: 222 },
    ':': { keyCode: 186, shiftKey: true },
    '+': { keyCode: 187, shiftKey: true },
    '<': { keyCode: 188, shiftKey: true },
    '_': { keyCode: 189, shiftKey: true },
    '>': { keyCode: 190, shiftKey: true },
    '?': { keyCode: 191, shiftKey: true },
    '~': { keyCode: 192, shiftKey: true },
    '{': { keyCode: 219, shiftKey: true },
    '|': { keyCode: 220, shiftKey: true },
    '}': { keyCode: 221, shiftKey: true },
    '"': { keyCode: 222, shiftKey: true },
    '\n': { keyCode: 13, shiftKey: true }
}